name: CICD-AKS-Build-Validation-Pipeline
on: workflow_dispatch
  # workflow_dispatch:
  # push:
  #   branches:
  #     - main
  # pull_request:
  #   branches:
  #     - main

jobs:
  CI-Dot-NetBuildValidation-Job:
    name: "CI-Dot-NetBuildValidation-Steps"
    runs-on: windows-latest
    
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: pwd
        shell: pwsh

      - name: Install latest .NET SDK
        uses: Elskom/setup-latest-dotnet@main
      
      - name: Restore NuGet Packages
        run: nuget restore WebApplication1.sln
        shell: pwsh

      # since i could'nt find the right action  to build the .net i have manaullay specified the location to build
      - name: Build
        run: '& "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" WebApplication1.sln /t:restore,build /p:Configuration=Release'
        shell: pwsh

      - name: Run Unit Tests
        run: dotnet test --no-build --configuration Release --verbosity normal

      # Dependabot Security Scan
      - name: Dependabot Alerts
        uses: actions/dependabot-alerts@v1

      # GitHub Advanced Security Code Scanning (CodeQL)
      - name: GitHub Code Scanning
        uses: github/codeql-action/analyze@v2
        with:
          category: "security-and-quality"

          

      # - name: Upload Artifact for Main CI/CD
      #   uses: actions/upload-artifact@v3
      #   with:
      #     name: build-output
      #     path: ./bin/Release
