name: PR Build Pipeline
on: workflow_dispatch

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: pwd
        shell: pwsh

      - name: Install latest .NET SDK
        uses: Elskom/setup-latest-dotnet@main

      # - name: Set MSBuild Path
      #   run: |
      #     echo "MSBuildExtensionsPath=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild" >> $GITHUB_ENV
      #   shell: pwsh
      - name: Install dependencies
        run: dotnet restore
        shell: pwsh
      # - name: Build
      #   run: dotnet build
      #   shell: pwsh


      
