name: PR Build Pipeline
on: workflow_dispatch

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Build the project
        run: dotnet build MySolution.sln
        working-directory: C:\github-agent\_work\WEBAPP-CICD-AKS-\WEBAPP-CICD-AKS-
        shell: pwsh
      - name: Debug Working Directory
        run: pwd
        shell: pwsh


      # - name: Restore NuGet Packages
      #   run: dotnet restore --ignore-failed-sources --force
      #   working-directory: ${{ github.workspace }}
      #   shell: pwsh


      # - name: Build the .NET Project
      #   run: dotnet build --configuration Release


