name: PR Build Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: windows-2022

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.0.x"

      - name: Install Visual Studio Build Tools (For Web Applications)
        run: |
          choco install visualstudio2019-buildtools --package-parameters "--add Microsoft.VisualStudio.Component.WebBuildTools --includeRecommended --includeOptional" -y

      - name: Restore NuGet Packages
        uses: zyactions/dotnet-restore@v1.1.0
        with:
          working-directory: ${{ github.workspace }}
          ignore-failed-sources: true
          force: true

      - name: Build the .NET Project
        run: dotnet build --configuration Release


