name: PR Build Pipeline
on: workflow_dispatch

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: self-hosted
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: pwd
        shell: pwsh

      - name: Install latest .NET SDK
        uses: Elskom/setup-latest-dotnet@main

      # - name: Set MSBuild Path
      #   run: |
      #     echo "MSBuildExtensionsPath=C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild" >> $GITHUB_ENV
      #   shell: pwsh
      - name: Restore NuGet Packages
        run: nuget restore WebApplication1.sln
        shell: pwsh

      - name: Build
        run: '& "C:\Program Files\Microsoft Visual Studio\2022\Community\MSBuild\Current\Bin\MSBuild.exe" WebApplication1.sln /t:restore,build /p:Configuration=Release'
        shell: pwsh

      # - name: Verify Directory
      #   run: |
      #     if (Test-Path "C:/github-agent/_work/WEBAPP-CICD-AKS-/WEBAPP-CICD-AKS") {
      #         echo "Directory exists."
      #         } else {
      #          echo "Directory NOT found!"; exit 1
      #         }
      #   shell: pwsh
      - name: Check Build Output
        run: |
          echo "Workspace Directory: ${{ github.workspace }}"
          Get-ChildItem -Path "${{ github.workspace }}" -Recurse
        shell: pwsh


      - name: Zip the Build Artifacts
        uses: papeloto/action-zip@v1
        with:
         files: C:\github-agent\_work\WEBAPP-CICD-AKS-\WEBAPP-CICD-AKS-\*
         recursive: true

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: compressed-data
          path: C:\github-agent\_work\WEBAPP-CICD-AKS-\WEBAPP-CICD-AKS-\result.zip



 
 
          

      
