name: PR Build Pipeline
on: workflow_dispatch

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: pwd
        shell: pwsh

      - name: ZyAction:.NET Restore
        # You may pin to the exact commit or the version.
        # uses: zyactions/dotnet-restore@bffc71e1a5275122a2795bf2912804f0185db27c
        uses: zyactions/dotnet-restore@v1.1.0
        with:
          working-directory: ${{ github.workspace }}  # Set the working directory (optional)
          workspace: WebApplication1.sln             # Path to solution file
          configfile: nuget.config                   # Specify NuGet configuration file (optional)
          ignore-failed-sources: true                # Only warn about failed sources
          force: true                                # Forces full dependency resolution
          force-evaluate: true                       # Reevaluates all dependencies
          use-lock-file: true                        # Enables project lock file usage
          lock-file-path: ${{ github.workspace }}/packages.lock.json  # Optional lock file path
          locked-mode: false                         # Allow updating the project lock file

      - name: Build DotNet
        uses: Elskom/build-dotnet@v1.1.1
        with:
          SOLUTION_FILE_PATH: ${{ github.workspace }}/WebApplication1.sln
          TEST: false   # Set to true if you want to run unit tests
          PACK: true    # Set to false if you don't want to create NuGet packages


