name: PR Build Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore NuGet Packages
        run: dotnet restore --ignore-failed-sources --force
        working-directory: ${{ github.workspace }}
        shell: pwsh


      - name: Build the .NET Project
        run: dotnet build --configuration Release


