name: PR Build Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Restore NuGet Packages
        uses: zyactions/dotnet-restore@v1.1.0
        with:
          working-directory: ${{ github.workspace }}
          ignore-failed-sources: true
          force: true
          shell: pwsh

      - name: Build the .NET Project
        run: dotnet build --configuration Release


