name: PR Build Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: windows-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"

      - name: Build the .NET Project
        run: dotnet build --configuration Release

      - name: Check for Vulnerable Dependencies
        run: dotnet list package --vulnerable

      # - name: Secret Scanning with TruffleHog
      #   uses: trufflesecurity/trufflehog@v3
      #   with:
      #     scan: repo
      #     base: HEAD~1
      #     head: HEAD
