name: PR Build Pipeline
on: workflow_dispatch

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: pwd
        shell: pwsh

      - name: Build DotNet
        uses: Elskom/build-dotnet@v1.1.1
        with:
          SOLUTION_FILE_PATH: ${{ github.workspace }}\WebApplication1.sln
          TEST: false   # Set to true if you want to run unit tests
          PACK: true    # Set to false if you don't want to create NuGet packages




