name: PR Build Pipeline

on:
  pull_request:
    branches:
      - master

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: windows-2022  # ✅ Use windows-2022 to ensure Visual Studio Build Tools are available

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Install .NET SDK
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "6.x"

      - name: Restore NuGet Packages
        uses: zyactions/dotnet-restore@v1.1.0
        with:
          working-directory: ${{ github.workspace }}  # ✅ Ensure it runs in the correct directory
          ignore-failed-sources: true  # ✅ Prevent failures due to missing sources
          force: true  # ✅ Force re-evaluation of dependencies

      - name: Build the .NET Project
        run: dotnet build --configuration Release

      - name: Check for Vulnerable Dependencies
        run: dotnet list package --vulnerable

