name: PR Build Pipeline
on: workflow_dispatch

jobs:
  PR_Validation:
    name: "Pull Request Validation Pipeline"
    runs-on: self-hosted

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Debug Working Directory
        run: pwd
        shell: pwsh

      - name: Install latest .NET SDK
        uses: Elskom/setup-latest-dotnet@main

      - name: Restore, Build, test, and pack
        uses: Elskom/build-dotnet@main
        with:
          TEST: true
          PACK: true


